# Generated by Django 5.1.5 on 2025-01-29 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="twofaapp.user",
                    ),
                ),
                ("twofa_secret", models.CharField(max_length=32)),
                ("twofa_name", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "userinfo",
            },
        ),
    ]
