# Generated by Django 5.1.5 on 2025-01-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twofaapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="twofa_passed",
            field=models.BooleanField(default=False),
        ),
    ]
