# Generated by Django 5.1.5 on 2025-01-29 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twofaapp", "0002_userinfo_twofa_passed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="user_id",
            new_name="user",
        ),
    ]
