# Generated by Django 5.1.5 on 2025-01-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jwtapp.user",
                    ),
                ),
                ("jwt_secret", models.CharField(max_length=10)),
                ("refresh_secret", models.CharField(max_length=10)),
                ("expired_at", models.DateTimeField()),
            ],
            options={
                "db_table": "user_status",
            },
        ),
    ]
