# Generated by Django 5.1.5 on 2025-01-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jwtapp.user')),
                ('twofa_secret', models.CharField(max_length=15)),
                ('twofa_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jwtapp.user')),
                ('jwt_secret', models.CharField(max_length=10)),
                ('refresh_secret', models.CharField(max_length=10)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
