# Generated by Django 5.1.5 on 2025-01-29 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jwtapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstatus",
            old_name="user_id",
            new_name="user",
        ),
    ]
