# Generated by Django 5.1.5 on 2025-01-19 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0002_userinfo_userstatus_delete_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jwtapp.user'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jwtapp.user'),
        ),
    ]
