# Generated by Django 5.1.5 on 2025-01-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='userttt',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfottt',
        ),
        migrations.AlterModelTable(
            name='userstatus',
            table='user_statusttt',
        ),
    ]
