# Generated by Django 5.1.5 on 2025-01-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='twofa_secret',
            field=models.CharField(max_length=32),
        ),
    ]
