# Generated by Django 5.1.5 on 2025-01-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, null=True, unique=True)),
                ('memo', models.TextField(blank=True, max_length=500)),
                ('win_cnt', models.IntegerField(default=0)),
                ('lose_cnt', models.IntegerField(default=0)),
                ('image_url', models.ImageField(default='default.png', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='user.friend')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='user.profile')),
            ],
            options={
                'db_table': 'friends',
            },
        ),
    ]
