# Generated by Django 5.1.5 on 2025-02-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, null=True, unique=True)),
                ('memo', models.TextField(blank=True, max_length=500)),
                ('image_url', models.ImageField(default='default.png', upload_to='images/')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_cnt', models.PositiveIntegerField(default=0)),
                ('total_cnt', models.PositiveIntegerField(default=0)),
                ('_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='user.profile')),
            ],
            options={
                'db_table': 'dashboard',
                'ordering': ['-win_cnt', 'total_cnt'],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user.profile')),
                ('friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user.profile')),
            ],
            options={
                'db_table': 'friends',
                'constraints': [models.UniqueConstraint(fields=('_user', 'friend'), name='unique_friendship')],
            },
        ),
    ]
