# Generated by Django 5.1.5 on 2025-01-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lose_cnt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='win_cnt',
        ),
    ]
