# Generated by Django 5.1.5 on 2025-02-03 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TempMatchRoom",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=32, unique=True)),
                ("start_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "db_table": "temp_match_room",
            },
        ),
        migrations.CreateModel(
            name="TempMatch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "round",
                    models.IntegerField(
                        choices=[(2, "Two"), (4, "Four"), (8, "Eight"), (16, "SIXTEEN")]
                    ),
                ),
                ("start_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_at", models.DateTimeField(default=None, null=True)),
                ("joined_user", models.IntegerField(default=0)),
                (
                    "winner",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameapp.user",
                    ),
                ),
                (
                    "winner_match",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameapp.tempmatch",
                    ),
                ),
                (
                    "match_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameapp.tempmatchroom",
                    ),
                ),
            ],
            options={
                "db_table": "temp_match",
            },
        ),
        migrations.CreateModel(
            name="TempMatchRoomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                (
                    "temp_match_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameapp.tempmatchroom",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="gameapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "temp_match_room_user",
            },
        ),
        migrations.CreateModel(
            name="TempMatchUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField(default=0)),
                (
                    "temp_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameapp.tempmatch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gameapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "temp_match_user",
            },
        ),
    ]
