# Generated by Django 5.1.6 on 2025-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempmatch",
            name="start_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
