# Generated by Django 5.1.6 on 2025-02-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameapp", "0002_alter_tempmatch_start_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempmatch",
            name="joined_user",
        ),
        migrations.AddField(
            model_name="tempmatch",
            name="is_with_ai",
            field=models.BooleanField(default=False),
        ),
    ]
