# Generated by Django 5.1.5 on 2025-01-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('profile_url', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authapp.user')),
                ('twofa_secret', models.CharField(max_length=32)),
                ('twofa_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authapp.user')),
                ('jwt_secret', models.CharField(max_length=10)),
                ('refresh_secret', models.CharField(max_length=10)),
                ('expired_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_status',
            },
        ),
    ]
