# Generated by Django 5.1.5 on 2025-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_42",
            field=models.BigIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
