# Generated by Django 5.1.5 on 2025-01-29 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0002_user_id_42_alter_user_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
